function [footLength, midFootLength, footWidth] = getIorFootSize(idxRef,...
                frameLeft, frameRight, c3dMarkersRef)



 rLenL = frameLeft.E'*(...
           0.5.*(c3dMarkersRef.('L_FM1')(idxRef,:)' ...
                +c3dMarkersRef.('L_FM5')(idxRef,:)')...
          -0.5.*(c3dMarkersRef.('L_FAL')(idxRef,:)' ...
                +c3dMarkersRef.('L_TAM')(idxRef,:)'));         
 midFootLengthL = rLenL(2,1);

 rLenR = frameRight.E'*(...
           0.5.*(c3dMarkersRef.('R_FM1')(idxRef,:)' ...
                +c3dMarkersRef.('R_FM5')(idxRef,:)') ...
          -0.5.*(c3dMarkersRef.('R_FAL')(idxRef,:)' ...
                +c3dMarkersRef.('R_TAM')(idxRef,:)'));         

 midFootLengthR = rLenR(2,1);

 rLenL = frameLeft.E'*(c3dMarkersRef.('L_FM2')(idxRef,:)' ...
                      -c3dMarkersRef.('L_FCC')(idxRef,:)');         
 footLengthL = rLenL(2,1);
 rLenR = frameRight.E'*(c3dMarkersRef.('R_FM2')(idxRef,:)' ...
                      -c3dMarkersRef.('R_FCC')(idxRef,:)');         
 footLengthR = rLenR(2,1);
 footLength = 0.5*(footLengthL+footLengthR);

 rWL = 0.5.*frameLeft.E'*(c3dMarkersRef.('L_FM1')(idxRef,:)'...
                      -c3dMarkersRef.('L_FM5')(idxRef,:)') ...
      +0.5.*frameLeft.E'*(c3dMarkersRef.('L_TAM')(idxRef,:)'...
                      -c3dMarkersRef.('L_FAL')(idxRef,:)');          
 footWidthL = rWL(1,1);
 rWR = 0.5.*frameRight.E'*(c3dMarkersRef.('R_FM5')(idxRef,:)'...
                      -c3dMarkersRef.('R_FM1')(idxRef,:)') ...
      +0.5.*frameRight.E'*(c3dMarkersRef.('R_FAL')(idxRef,:)'...
                      -c3dMarkersRef.('R_TAM')(idxRef,:)');         
 footWidthR = rWR(1,1);
 here=1;

 midFootLength = 0.5*(midFootLengthL+midFootLengthR);
 footWidth  = 0.5*(footWidthL+footWidthR);